package com.api.cadastroScore;

import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.crypto.password.PasswordEncoder;

import com.api.cadastroScore.auth.jwt.model.UsuarioModel;
import com.api.cadastroScore.auth.jwt.repository.UsuarioRepository;
import com.api.cadastroScore.model.Pessoa;
import com.api.cadastroScore.repository.PessoaRepository;

@SpringBootApplication
public class CadastroScoreApplication {
  
	public static void main(String[] args) {
		SpringApplication.run(CadastroScoreApplication.class, args);
	}
	
	@Bean
	CommandLineRunner inicializaBancoDeDados(PessoaRepository pessoaRepository, UsuarioRepository usuarioRepository) {
	    return args -> {
	        pessoaRepository.deleteAll();
          Pessoa pessoa = new Pessoa();
          pessoa.setId(null);
          pessoa.setNome("Adriano Junior");
          pessoa.setTelefone("111111111");
          pessoa.setIdade(35);
          pessoa.setCep("1010101010");
          pessoa.setEstado("Estado 1");
          pessoa.setCidade("Cidade 1");
          pessoa.setBairro("Bairro 1");
          pessoa.setLogradouro("Rua Primeiro de janeiro");
          pessoa.setScore(110);
          pessoa.setScoreDescricao("Insuficiente");
          pessoaRepository.save(pessoa);
          pessoa.setId(null);
          pessoa.setNome("Juliano Marques");
          pessoa.setTelefone("222333444");
          pessoa.setIdade(52);
          pessoa.setCep("323232343434");
          pessoa.setEstado("Estado 2");
          pessoa.setCidade("Cidade 2");
          pessoa.setBairro("Bairro 2");
          pessoa.setLogradouro("Rua 2 de 2");
          pessoa.setScore(220);
          pessoa.setScoreDescricao("Inaceitável");
          pessoaRepository.save(pessoa);
          pessoa.setId(null);
          pessoa.setNome("Adriano Santos");
          pessoa.setTelefone("333333333");
          pessoa.setIdade(25);
          pessoa.setCep("3030303030");
          pessoa.setEstado("Estado 3");
          pessoa.setCidade("Cidade 3");
          pessoa.setBairro("Bairro 3");
          pessoa.setLogradouro("Rua 3 de 3");
          pessoa.setScore(330);
          pessoa.setScoreDescricao("Inaceitável");
          pessoaRepository.save(pessoa);
          pessoa.setId(null);
          pessoa.setNome("Caroline Santos");
          pessoa.setTelefone("444444444");
          pessoa.setIdade(24);
          pessoa.setCep("3030303030");
          pessoa.setEstado("Estado 4");
          pessoa.setCidade("Cidade 4");
          pessoa.setBairro("Bairro 4");
          pessoa.setLogradouro("Rua 4 de 4");
          pessoa.setScore(440);
          pessoa.setScoreDescricao("Inaceitável");
          pessoaRepository.save(pessoa);          
          pessoa.setId(null);
          pessoa.setNome("Caroline Santos");
          pessoa.setTelefone("555555555");
          pessoa.setIdade(24);
          pessoa.setCep("5050505050");
          pessoa.setEstado("Estado 5");
          pessoa.setCidade("Cidade 5");
          pessoa.setBairro("Bairro 5");
          pessoa.setLogradouro("Rua 5 de 5");
          pessoa.setScore(550);
          pessoa.setScoreDescricao("Aceitável");
          pessoaRepository.save(pessoa);          
          pessoa.setNome("Marcelo Antonio");
          pessoa.setTelefone("777777777");
          pessoa.setIdade(35);
          pessoa.setCep("7070707070");
          pessoa.setEstado("Estado 7");
          pessoa.setCidade("Cidade 7");
          pessoa.setBairro("Bairro 7");
          pessoa.setLogradouro("Rua 7 de 7");
          pessoa.setScore(770);
          pessoa.setScoreDescricao("Recomendável");
          pessoaRepository.save(pessoa);         
          pessoa.setId(null); 
          pessoa.setNome("Gustavo Torres");
          pessoa.setTelefone("888888888");
          pessoa.setIdade(53);
          pessoa.setCep("8080808080");
          pessoa.setEstado("Estado 8");
          pessoa.setCidade("Cidade 8");
          pessoa.setBairro("Bairro 8");
          pessoa.setLogradouro("Rua 8 de 8");
          pessoa.setScore(880);
          pessoa.setScoreDescricao("Recomendável");
          pessoaRepository.save(pessoa);     
          pessoa.setId(null);     
          pessoa.setNome("Joana Maria");
          pessoa.setTelefone("999999999");
          pessoa.setIdade(41);
          pessoa.setCep("9090909090");
          pessoa.setEstado("Estado 9");
          pessoa.setCidade("Cidade 9");
          pessoa.setBairro("Bairro 9");
          pessoa.setLogradouro("Rua 9 de 9");
          pessoa.setScore(990);
          pessoa.setScoreDescricao("Recomendável");
          pessoaRepository.save(pessoa);          
          pessoa.setId(null);
          pessoa.setNome("Maria Oliveira");
          pessoa.setTelefone("1919191919");
          pessoa.setIdade(45);
          pessoa.setCep("0101010101");
          pessoa.setEstado("Estado 10");
          pessoa.setCidade("Cidade 10");
          pessoa.setBairro("Bairro 10");
          pessoa.setLogradouro("Rua 10 de 10");
          pessoa.setScore(150);
          pessoa.setScoreDescricao("Insuficiente");
          pessoaRepository.save(pessoa);          
          pessoa.setId(null);
          pessoa.setNome("Miguel Orlando");
          pessoa.setTelefone("1212121212");
          pessoa.setIdade(32);
          pessoa.setCep("123123123");
          pessoa.setEstado("Estado 11");
          pessoa.setCidade("Cidade 11");
          pessoa.setBairro("Bairro 11");
          pessoa.setLogradouro("Rua 11 de 11");
          pessoa.setScore(570);
          pessoa.setScoreDescricao("Aceitável");
          pessoaRepository.save(pessoa);          
          pessoa.setId(null);
          pessoa.setNome("João dos Santos");
          pessoa.setTelefone("1313131313");
          pessoa.setIdade(26);
          pessoa.setCep("321321321");
          pessoa.setEstado("Estado 12");
          pessoa.setCidade("Cidade 12");
          pessoa.setBairro("Bairro 12");
          pessoa.setLogradouro("Rua 12 de 12");
          pessoa.setScore(870);
          pessoa.setScoreDescricao("Recomendável");
          pessoaRepository.save(pessoa);  
          pessoa.setId(null);        
          pessoa.setNome("Adriane Marcondes");
          pessoa.setTelefone("1414141414");
          pessoa.setIdade(25);
          pessoa.setCep("145145145");
          pessoa.setEstado("Estado 13");
          pessoa.setCidade("Cidade 13");
          pessoa.setBairro("Bairro 13");
          pessoa.setLogradouro("Rua 13 de 13");
          pessoa.setScore(450);
          pessoa.setScoreDescricao("Inaceitável");
          pessoaRepository.save(pessoa);          
          pessoa.setId(null);
          pessoa.setNome("Juliana Silva");
          pessoa.setTelefone("45451515164");
          pessoa.setIdade(24);
          pessoa.setCep("80808080877");
          pessoa.setEstado("Estado 14");
          pessoa.setCidade("Cidade 14");
          pessoa.setBairro("Bairro 14");
          pessoa.setLogradouro("Rua 14 de 14");
          pessoa.setScore(650);
          pessoa.setScoreDescricao("Aceitável");
          pessoaRepository.save(pessoa);        
          pessoa.setId(null);  
          pessoa.setNome("Aline Santos");
          pessoa.setTelefone("521452145");
          pessoa.setIdade(27);
          pessoa.setCep("8087070800");
          pessoa.setEstado("Estado 15");
          pessoa.setCidade("Cidade 15");
          pessoa.setBairro("Bairro 15");
          pessoa.setLogradouro("Rua 15 de 15");
          pessoa.setScore(185);
          pessoa.setScoreDescricao("Insuficiente");
          pessoaRepository.save(pessoa);     
          pessoa.setId(null);     
          pessoa.setNome("Carlos Jordão");
          pessoa.setTelefone("7845125487");
          pessoa.setIdade(24);
          pessoa.setCep("986532235689");
          pessoa.setEstado("Estado 16");
          pessoa.setCidade("Cidade 16");
          pessoa.setBairro("Bairro 16");
          pessoa.setLogradouro("Rua 16 de 16");
          pessoa.setScore(950);
          pessoa.setScoreDescricao("Recomendável");
          pessoaRepository.save(pessoa);
          usuarioRepository.deleteAll();
          UsuarioModel usuario = new UsuarioModel();
          usuario.setNomeUsuario("ADMIN");
          usuario.setSenha(getPasswordEncoder().encode("ADMIN123"));
          usuario.getRoles().add("ROLE_ADMIN");
          usuarioRepository.save(usuario);
          usuario.setId(null);
          usuario.setNomeUsuario("user");
          usuario.setSenha(getPasswordEncoder().encode("user123"));
          usuario.getRoles().clear();
          usuario.getRoles().add("ROLE_USER");
          usuarioRepository.save(usuario);
	    };
	}

  @Bean      
  public PasswordEncoder getPasswordEncoder() {
    return new BCryptPasswordEncoder();
  }

}
